### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by judhat2** [onedr0p/manage-this-node#11]
I am not familiar with npm.  Any idea how to fix this? I am running Ubuntu 14.04.3.
```
user@HTPC:~/manage-this-node# npm start

> manage-this-node@0.0.0 start /user/manage-this-node
> node ./bin/www

sh: 1: node: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

**Comment by jayrox** [comment]
based on details found here: http://plaidzooks.tumblr.com/post/36894116867/using-nodejs-on-debianubuntu-systems

run `sudo apt-get install nodejs-legacy`

that should fix the problem

**Comment by judhat2** [comment]
Thanks!! That fixed it.
