### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by jwmoss** [onedr0p/manage-this-node#14]
Any possibility? Awesome job, by the way! Had it up and running in minutes!

**Comment by onedr0p** [comment]
Hi! HTTPS can be handled best by putting this behind a reverse proxy via nginx or apache. That is how all SSL node webapps are generally handled.

**Comment by jwmoss** [comment]
Ok thanks! I'll approach it through those methods. 

Sent from iPhone




On Mon, Jan 18, 2016 at 9:00 PM -0800, "Devin Buhl" <notifications@github.com> wrote:












Hi! HTTPS can be handled best by putting this behind a reverse proxy via nginx or apache. That is how all SSL node webapps are generally handled.

**Comment by jayrox** [comment]
https is outside the current scope of this app.
