### ISSUE TITLE
Show commits (updates) in-app via modal (iFrame not possible because GitHub denies them)

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/manage-this-node#18]
Semi-working in `commit_scraper` branch. This isn't how I want it to function in it's current state. I think setting up a route called /commits and a ajax request (on modal button press) to do the scraping is key. This why the app still works if the scraper can't reach GitHub XD

**Comment by onedr0p** [comment]
I updated master with a newer version in what I described above. It just needs a little more formatting to make it look pretty.

**Comment by Hellowlol** [comment]
Use the github api?

**Comment by onedr0p** [comment]
Using the github API requires a token set and created by the user if I'm not mistaken. Not everyone is signed up here, let alone wanted to go thru that process.

**Comment by Hellowlol** [comment]
Nope, you get 60 requests pr hour unregistered. See https://developer.github.com/v3/rate_limit/

**Comment by onedr0p** [comment]
Ah, interesting, this would be much better. I'll take a look :)

**Comment by jayrox** [comment]
i have an even better idea:
how about we make a github pages branch and use that for the change log.
i dont think the pages branch gets the header that blocks the iframe
