### ISSUE TITLE
Ubuntu LTS 14.04.3- sudo command required for install forever

### ISSUE THREAD

**Issue by n0doubt** [onedr0p/manage-this-node#20]
If using the install forever option according to the installation instructions, the installation fails because the system is trying to access` /usr/lib/modules` and is unable to. Installation succeeds by running `sudo npm install forever -g`

**Comment by onedr0p** [comment]
Right, anytime you need to install a global package in node on *nix you need to use the sudo command, it adds the symlink/files to /usr/bin.
