### ISSUE TITLE
Unable to start - Cannot read property 'length'

### ISSUE THREAD

**Issue by smiller82** [onedr0p/manage-this-node#30]
Running NPM Start triggers the following errors.  I had NodeJS 4.6.x installed and downgraded to NodeJS 4.2.x as listed under dependencies but no luck.

> TypeError: Cannot read property 'length' of undefined at pathtoRegexp (C:\...\manage-this-node\node_modules\express\node_modules\path-to-regexp\index.js:63:48)
>     at new Layer (C:\...\manage-this-node\node_modules\express\lib\router\layer.js:45:17)
>     at Function.use (C:\...\manage-this-node\node_modules\express\lib\router\index.js:464:17)
>     at EventEmitter.<anonymous> (C:\...\manage-this-node\node_modules\express\lib\application.js:219:21)
>     at Array.forEach (native)
>     at EventEmitter.use (C:\...\manage-this-node\node_modules\express\lib\application.js:216:7)
>     at Object.<anonymous> (C:\...\manage-this-node\app.js:29:5)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
> 
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
> npm ERR! node v4.2.6
> npm ERR! npm  v2.14.12
> npm ERR! code ELIFECYCLE
> npm ERR! manage-this-node@0.1.1 start: `node ./bin/www`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the manage-this-node@0.1.1 start script 'node ./bin/www'.
> npm ERR! This is most likely a problem with the manage-this-node package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node ./bin/www
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls manage-this-node
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\...\manage-this-node\npm-debug.log

This is the output of npm-debug.log

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'start' ]
> 2 info using npm@2.14.12
> 3 info using node@v4.2.6
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info prestart manage-this-node@0.1.1
> 6 info start manage-this-node@0.1.1
> 7 verbose unsafe-perm in lifecycle true
> 8 info manage-this-node@0.1.1 Failed to exec start script
> 9 verbose stack Error: manage-this-node@0.1.1 start: `node ./bin/www`
> 9 verbose stack Exit status 1
> 9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at EventEmitter.emit (events.js:172:7)
> 9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at ChildProcess.emit (events.js:172:7)
> 9 verbose stack     at maybeClose (internal/child_process.js:821:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 10 verbose pkgid manage-this-node@0.1.1
> 11 verbose cwd C:\...\manage-this-node
> 12 error Windows_NT 6.3.9600
> 13 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
> 14 error node v4.2.6
> 15 error npm  v2.14.12
> 16 error code ELIFECYCLE
> 17 error manage-this-node@0.1.1 start: `node ./bin/www`
> 17 error Exit status 1
> 18 error Failed at the manage-this-node@0.1.1 start script 'node ./bin/www'.
> 18 error This is most likely a problem with the manage-this-node package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     node ./bin/www
> 18 error You can get their info via:
> 18 error     npm owner ls manage-this-node
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]
>

**Comment by mgluc11** [comment]
I am having the same issue. Windows 10, npm v2.15.9 ; nodejs 4.6.x

**Comment by messyfresh** [comment]
Same issue here. Win 10, node v6.5.0 npm 3.9.3.  It seems that the latest commit is requiring a specific config from app.js on line 29
```
app.use(config.app.urlbase, router);
```

Its trying to reference a urlbase from the config object, but that object doesn't exist
