### ISSUE TITLE
Create a favicon

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/manage-this-node#5]
Anyone want to help contribute one?

**Comment by Tenzinn3** [comment]
Sure, I'll do it tomorrow.

**Comment by onedr0p** [comment]
Thanks, looking forward :)

**Comment by mannibis** [comment]
Just out of curiosity, is there a way to add a favicon to manage-this-node? I placed my "favicon.ico" into /public/img but no luck.

**Comment by jayrox** [comment]
You would need to place the icon in `/public` instead of `/public/img`
You will also need to uncomment line 15 in `app.js`

`app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));`

**Comment by onedr0p** [comment]
@mannibis if you get this added, feel free to send PR. Thanks!

**Comment by mannibis** [comment]
Thanks guys, that worked. 
@onedr0p: I had made a custom favicon for my personal site, which is what I'm using. I'll see if I can whip something up for manage-this-node though. Thanks for the app :)

**Comment by NathanTheGr8** [comment]
@onedr0p @mannibis I just forked this repo and the docker one and set up my own favicon for my personal site. I will also try to work on a logo/favicon for this app.

**Comment by NathanTheGr8** [comment]
<img width="694" alt="favicon" src="https://cloud.githubusercontent.com/assets/2585114/17706455/c17c9a94-63a1-11e6-816c-5f956495d403.png">

**Comment by NathanTheGr8** [comment]
thoughts on that?

**Comment by onedr0p** [comment]
Looks good.

**Comment by NathanTheGr8** [comment]
I will pass the file through http://realfavicongenerator.net/ and generate the assets to add. Eventually I would like to let the user upload what ever pic they want and call their api and generate all the custom assets.

**Comment by aroundmyroom** [comment]
Nice :/)

Verstuurd vanaf mijn iPhone
